#!/bin/sh -x

OUTPUT_DIR="deps"
TMP_FILE_TMPL="/tmp/cpk.XXXX"
TMP_FILE=""

usage() {
	echo "cpk: usage"
	exit 0;
}

install() {
	local directory="$1"
	if [ ! -f "$directory/.depends" ]; then
		echo "No .depends file."
		return
	fi
	while IFS= read line; do
		if grep -F "$line" "$TMP_FILE" > /dev/null 2>&1; then
			echo "Circular dependency detected: \"$line\""
			continue
		fi
		echo "$line" >> "$TMP_FILE"
		if echo "$line" | grep -q "git://"; then
			git submodule add "$line" "$OUTPUT_DIR/$(basename "$line")"
			git submodule init
			git submodule update
		elif stat "$line" > /dev/null 2>&1; then
			cp -R "$line" "$OUTPUT_DIR/$(basename "$line")"
		else
			curl -q --location -O "$line"
			unzip -q -u "$(basename "$line")" -d "$OUTPUT_DIR"
			rm "$(basename "$line")"
		fi
		# escape all slashes
		local escaped_line="$(echo "$line" | sed 's/\//\\\//g')"
		sed -i '/'"$escaped_line"'/d' "$TMP_FILE"
	done < "$directory/.depends"
}

do_install() {
	TMP_FILE="$(mktemp "$TMP_FILE_TMPL")"
	install "$1"
	rm "$TMP_FILE"
}

while getopts "o:" flag; do
	case $flag in
		o ) OUTPUT_DIR=$OPTARG
			;;
		? ) usage $0 ;;
	esac
done
shift $(( OPTIND - 1 ))

do_install "$PWD"
