#!/bin/sh

OUTPUT_DIR="deps"

usage() {
    echo "cpk: usage"
    exit 0;
}

install() {
    if [ ! -f ".metadata" ]; then
        echo "No .metadata file."
        return
    fi
    . "$PWD/.metadata"
    curl --location -O "$DEPS"     
    unzip "$(basename $DEPS)" -d "$OUTPUT_DIR"
}

while getopts "o:" flag; do
   case $flag in
       o ) OUTPUT_DIR=$OPTARG
           ;;
       ? ) usage $0 ;;
   esac 
done
shift $(( OPTIND - 1 ))

install
